### PR TITLE
upgraded to Jedis 2.0.0 + new commands + formating/naming/indentations fixes

### PR DESCRIPTION
**Pull request by mpenet**
Hello, 

This patch adds support for jedis 2.0.0, including new commands it introduces. 
I also took the liberty to change some function names to match the jedis counterparts more closely and also fixed indentation.

### CODE REVIEW

**Comment by sunng87** [comment]
Please merge this patch.

**Comment by mmcgrana** [comment]
Hi Max, thanks for this patch. I think there is good stuff here, but I have a few comments:
- clj-redis is a Clojure Redis library, not necessarily a wrapper around Jedis. For this reason the public function names should correspond to the Redis interface, not Jedis: http://redis.io/commands. For example, the Redis function names are `GETRANGE` and `ZRANGEBYSCORE` 
- In general, I prefer the formatting and indentation as-is (1 ";", compressed left whitespace).
- Are there any user-facing implications of the move to Jedis 2.0.0?

**Comment by sunng87** [comment]
@mmcgrana

There are two new commands for sorted set: `ZRANGE-WITHSCORE` and `ZREVRANGE-WITHSCORES`. I would like to see them available in next clj-redis release.

**Comment by mpenet** [comment]
Hello Mark, 
- I agree with you, i didn't check the redis commands reference first, i just assumed they were the same as jedis'
- about the formatting, I am just used to the emacs ;; indent style but it doesn't really matter.
- I made this change for the new commands, it also fixes a number of bugs apparently. 

Following the logic of redis signatures we should dispatch to the appropriate fn depending on what we want, maybe something along these lines: 

ZRANGE key start stop [WITHSCORES]
defn zrange [p k start stop & {:key [withscores]}] ... ) 

ZRANGEBYSCORE key min max [WITHSCORES] [LIMIT offset count]
defn zrangebyscore [p k min max & {:key [withscores limit offset count]}] ... ) 

Would that be ok ?

**Comment by mmcgrana** [comment]
Yes, these look good to me:

```
defn zrange [p k start stop & {:key [withscores]}] ... )
defn zrangebyscore [p k min max & {:key [withscores limit offset count]}] ... )
```

We could take the chance to normalize all function signatures to that style as well.

**Pull request closed without merging**
