### PR TITLE
add some missing commands + connection check on borrow

### PR DESCRIPTION
**Pull request by mpenet**
Hello Mark, 

I have added some commands that were missing, I also changed the pool to JedisPool and set testOnBorrow to true to ensure that the connections are always valid.

I also changed the code a bit in some place, to allow to use a macro later on to remove all the (lease p (fn [^Jedis j] redundancies for instance (and to make pipeline/transactions support easier maybe, because of the type hints)

### CODE REVIEW

**Comment by mpenet** [comment]
Let me know if you want me to modify anything else on this request.

**Comment by mpenet** [comment]
fingerfart on the "Comment and Close" button , sorry

**Comment by mmcgrana** [comment]
I am getting a class not found exception on the JedisPoolConfig change. Any ideas what I might be doing wrong? Otherwise the changeset looks good to me:

<pre>

~/state/repos/clj-redis(rebase) $ lein clean
Cleaning up.
~/state/repos/clj-redis(rebase) $ lein deps
Copying 3 files to /Users/mmcgrana/state/repos/clj-redis/lib
~/state/repos/clj-redis(rebase) $ clj
Clojure 1.3.0-alpha4
user=> (require '[clj-redis.client :as redis])
ClassNotFoundException redis.clients.jedis.JedisPoolConfig  java.net.URLClassLoader$1.run (URLClassLoader.java:202)
user=> (import 'redis.clients.jedis.JedisPoolConfig)
ClassNotFoundException redis.clients.jedis.JedisPoolConfig  java.net.URLClassLoader$1.run (URLClassLoader.java:202)
user=> (import 'org.apache.commons.pool.impl.GenericObjectPool)
org.apache.commons.pool.impl.GenericObjectPool
user=> ^D
~/state/repos/clj-redis(rebase) $ git log
commit 87416fea057a00b52e9a0ac67e42428f75ea7af6
Author: mpenet <max.penet@gmail.com>
Date:   Mon Apr 18 10:04:06 2011 +0200

    add missing commands

commit a019aba3a925add869ebf0db33866196e48a9175
Author: mpenet <max.penet@gmail.com>
Date:   Mon Apr 18 09:57:38 2011 +0200

    add test-on-borrow as config opt

commit aa075208ce94ec3b0646b6e5d4df845ee88236e7
Author: mpenet <max.penet@gmail.com>
Date:   Mon Apr 18 09:30:43 2011 +0200

    use JedisPoolConfig instead of apache GenericObjectPool$Config

commit 1467876647ae00c09bea334c3cb06a7ea60d163c
Author: Mark McGranaghan <mmcgrana@gmail.com>
Date:   Wed Mar 16 04:34:26 2011 -0700

    0.0.9
</pre>

**Comment by mpenet** [comment]
My bad, I was using a more recent version of Jedis. I updated the project file.

**Comment by mmcgrana** [comment]
Great, merged and incorporated into 0.0.10 release.

**Pull request closed without merging**
